const milo = [
  "cool",
  "well kempt",
  "badass",
  "intelligent",
  "charismatic",
  "resourceful",
  "adventurous",
  "creative",
  "loyal",
  "resilient",
  "witty",
  "compassionate",
  "innovative",
  "determined",
  "perceptive",
  "fearless",
  "brilliant",
  "visionary",
  "versatile",
  "strategic",
  "eloquent",
  "adaptable",
  "insightful",
  "authentic",
  "dynamic",
  "inspiring",
  "thoughtful",
  "passionate",
  "tech-savvy",
  "problem-solver",
  "l337 hacker",
  "code ninja",
  "debugging wizard",
  "algorithm master",
  "full-stack virtuoso",
  "git wizard",
  "keyboard shortcut champion",
  "clean code advocate",
  "refactoring genius",
  "10x developer",
];
